### ISSUE TITLE
View most listened genres

### ISSUE THREAD

**Issue by isgo5880** [CSCI3308-Group-3-Music-Recommendations/Music-Recommendation-App#6]
As a user, if my account is synced to Spotify, I should be able to see the genres that I listen to the most on my account/home page.

**Comment by liviah12** [comment]
Acceptance criteria: As a user, if I have synced my Spotify account (in profile page), when I click on "Top Genres" on the navbar then I will be taken to a page that displays my top 10 genres

**Comment by d9eman** [comment]
No longer doing this.
